- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Enable and Start Docker Service
  service:
    name: docker
    state: started
    enabled: yes
