- name: Clone E-commerce App Repository
  git:
    repo: https://github.com/moseskisoi/ip2.git
    dest: /var/www/ecommerce

- name: Build and Run Docker Containers
  shell: docker-compose up -d
  args:
    chdir: /var/www/ecommerce
